# Generated by Django 4.1.4 on 2022-12-20 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
                ('QuotaLimit', models.IntegerField()),
                ('QuotaSpent', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='translation',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('InputText', models.CharField(max_length=200)),
                ('OutputText', models.CharField(max_length=200)),
                ('FromUserId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.user')),
            ],
        ),
    ]
